### ISSUE TITLE
Version uplift needed in model_processing examples needed?

### ISSUE THREAD

**Issue by josor001** [SeelabFhdo/lemma#51]
Because our sonatype repository is currently down and I wanted to do a local build, I just noticed that the dependency versions in `https://github.com/SeelabFhdo/lemma/tree/main/examples/model-processing` are still sitting at LEMMA v0.8.0 (build crashed cause v0.8.0 were not accessible locally nor from the temporary down repo). The build will work again when the sonatype repo is back up, however, this made me curious if we need/should  do a version uplift to 0.8.5 for those model processing examples?
This may also concern other projects in the examples folder.

**Comment by frademacher** [comment]
Yes, this is by intent. The model processor example at https://github.com/SeelabFhdo/lemma/tree/main/examples/model-processing documents the approach to implement model processors with LEMMA's model processing framework prior to its refactoring in version 0.8.5-SNAPSHOT. This circumstance is also indicated by the first lines of the example processor's [README](https://github.com/SeelabFhdo/lemma/blob/main/examples/model-processing/README.md):

*Note that this example project only serves documentary purposes for the implementation of model processors prior to the refactoring of LEMMA's model processing framework with LEMMA release 0.8.5-SNAPSHOT. For the latest approach on how to implement model processors leveraging the framework, please have a look at the example project model-processing-latest.*

More precisely, this example project for LEMMA version 0.8.0-SNAPSHOT exists mainly for historical reasons and as additional information to Issue https://github.com/SeelabFhdo/lemma/issues/42. However, since we have the refactored version of the framework at hand now (cf. https://github.com/SeelabFhdo/lemma/tree/main/examples/model-processing-latest) and Issue https://github.com/SeelabFhdo/lemma/issues/42 seems deprecated, I guess it's fine to replace the "old" example project with the refactored version and we should do that together with the release of the next LEMMA version. I'll leave this issue open as a reminder.

To fix your issue with building the project locally even with the missing Nexus repository remove the line `examples/model-processing` from your local [`lemma-build-modules.txt`](https://github.com/SeelabFhdo/lemma/blob/main/build/lemma-build-modules.txt).

**Comment by josor001** [comment]
thx for clarifying :)!

**Comment by frademacher** [comment]
As written above, I'd like to keep the issue open as a reminder for the eventual removal of the old model processing example with the next LEMMA release.

**Comment by frademacher** [comment]
As discussed above, I just removed the old model processing example with commit b9ce7cf11c94e90d16bbeaf79160e9eee92b8575.
